foodie_app/urls.py
from . import views 
from django.urls import path 

# namespacing urls 
app_name = 'food'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:item_id>/', views.detail, name='detail'),
    path('item/', views.item, name='item'),
]

menu_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('foodie_app.urls')),
]

foodie_app/models.py
from django.db import models

# Create your models here.
class Item(models.Model):
    
    def __str__(self):
        return self.item_name 
	
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()    

foodie_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Item
from django.template import loader

# create views here 

def index(request):
    item_list = Item.objects.all()
    
    context = {
      'item_list': item_list,
    }
    return render(request, 'foodie_app/index.html', context)

def item(request):
    return HttpResponse('<h2>This is an item</h2>')

def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = { 
        'item': item,
    }

    return render(request, 'foodie_app/detail.html', context)

foodie_app/templates/foodie_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible">
    <title>Foodie App</title>
    <link rel="stylesheet" href="{% static 'foodie_app/style.css' %}"/>
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <a href="#" class="navbar-brand">Foodie App</a>
      <div class="navbar">
        <a class="nav-item nav-link" href="#">Menu Item</a>
        <a class="nav-item nav-link" href="#">Menu Item</a>
        <a class="nav-item nav-link" href="#">Menu Item</a>
      </div>
    </nav>
    {% block body %}

    {% endblock %}
  </body>
</html>

foodie_app/templates/foodie_app/detail.html
{% extends 'foodie_app/base.html' %}

{% block body %}

  <h1>{{ item.name }}</h1>
  <h2>{{ item.item_desc }}</h2>
  <h3>{{ item.item_price }}</h3>

{% endblock %}

foodie_app/templates/foodie_app/index.html
{% extends 'foodie_app/base.html' %}
<!DOCTYPE html>
<html lang="en">
 <head></head>
 <body>
   {% block body %}

      {% for item in item_list %}
        <ul>
         <a href={% url 'food:detail' item.id %}>{{ item.id }} - {{ item.item_name }}</a>
        </ul>
      {% endfor %}

   {% endblock %}
 </body>
</html>